### ISSUE TITLE
generación de landing con html

### ISSUE THREAD

**Issue by marianaCodelium** [Codelium-team/TeachingLanding#2]
### 2. Estructura HTML

**Descripción: Desarrollar la estructura básica de la página utilizando HTML5.**

### Tareas:

- [x] Crear el esqueleto de la página.
- [x] Incluir todas las secciones necesarias: Barra de navegación, Inicio, Nosotros, Categorías de Productos, Principales Productos, Contacto, Redes Sociales, Información de Atención y Footer.
- [x] Asegurar la semántica y accesibilidad del HTML.

**_-------------------------------------------------------------------------------------------------------------------------------------------_**

**Instrucciones para Contabilizar Horas de Desarrollo**

1. **Inicio de Desarrollo**
   - **Comentario:** `Inicio de desarrollo a las [hora] con fecha [fecha]`
   - **Ejemplo:** `Inicio de desarrollo a las 09:00 con fecha 08/11/2024`

2. **Pausa de Desarrollo**
   - **Comentario:** `Pausa de desarrollo a las [hora] con fecha [fecha]`
   - **Ejemplo:** `Pausa de desarrollo a las 11:00 con fecha 08/11/2024`

3. **Retoma de Desarrollo**
   - **Comentario:** `Retomo de desarrollo a las [hora] con fecha [fecha]`
   - **Ejemplo:** `Retomo de desarrollo a las 13:00 con fecha 08/11/2024`

4. **Término de Desarrollo**
   - **Comentario:** `Término de desarrollo a las [hora] con fecha [fecha]. Se trabajó un total de [horas] horas con [minutos] minutos`
   - **Ejemplo:** `Término de desarrollo a las 17:00 con fecha 08/11/2024. Se trabajó un total de 6 horas con 0 minutos`

**Comment by javoc88** [comment]
Inicio de desarrollo a las 17:00 con fecha 25/11/2024.
Término de desarrollo a las 18:00 con fecha 25/11/2024. Se trabajó un total de 1 hora.
